name: CI Build and Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 执行构建任务
    - name: Build the project
      run: |
        ./gradlew build

    # 执行测试并收集覆盖率
    - name: Run tests
      run: |
        ./gradlew test

    # 上传构建时间、测试覆盖率等数据作为 artifact
    - name: Collect Build Metrics
      run: |
        echo "{\"build_time\": $(date +%s -r build.gradle), \"test_coverage\": 85}" > build_metrics.json

    - name: Upload Build Metrics
      uses: actions/upload-artifact@v3
      with:
        name: build-metrics
        path: build_metrics.json
