name: CI Build and Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 JDK 版本
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # 或者 'zulu'

    # 缓存 Maven 的本地仓库，提升构建速度
    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 安装依赖并构建项目
    - name: Build the project
      run: mvn clean install

    # 如果需要测试覆盖率，可以运行测试
    - name: Run tests
      run: mvn test

    # 收集构建时间或覆盖率等数据（可选）
    - name: Collect Build Metrics
      run: |
        echo "Build completed successfully"
